### ISSUE TITLE
How can i change radius? 

### ISSUE THREAD

**Issue by editor83** [i-schuetz/PieCharts#1]
I want to change chart radius size but i can't do it.

let viewLayer = PieViewLayer()
let settings = PieViewLayerSettings()
settings.viewRadius = 70
settings.hideOnOverflow = false
viewLayer.settings = settings
        
responseChart.layers = [viewLayer, responseTextLayer]

is'nt it true?

**Comment by i-schuetz** [comment]
`PieViewLayer` is not the chart, it's a layer containing custom view overlays.

To set the radius use `innerRadius` and `outerRadius` from `PieChart`. If you don't want to use `innerRadius` (i.e. gap at the center) set this to 0.

If possible please update the pod, I just released 0.0.3 and now these properties can be set in storyboards / directly in `PieChart` (`PieChartSettings` was removed).

**Comment by editor83** [comment]
Ok Ivan. I did it. Thank you so much. Great chart.
