### ISSUE TITLE
Animation duration to 0, Infos are not displayed

### ISSUE THREAD

**Issue by Aximem** [i-schuetz/PieCharts#10]
I wanted to remove animation for ChartView : 
`chartView.animDuration = 0.0`

Infos are not displayed anymore, you can test it by adding this line in "CustomViewsDemo".

**Comment by i-schuetz** [comment]
Fixed! Sorry for the delay!

Until the next release you can use master directly:
```ruby
pod 'PieCharts', :git => 'https://github.com/i-schuetz/PieCharts.git'
```

**Comment by Aximem** [comment]
Thanks ;)
