### ISSUE TITLE
Rotating the pie chart

### ISSUE THREAD

**Issue by Brandon-316** [i-schuetz/PieCharts#11]
Hi Ivan, I am curious if there would be a way to make the pie chart rotate so the slice selected is at the top position when it expands.

**Comment by i-schuetz** [comment]
I will take a look into this in the next days, thanks!

**Comment by Brandon-316** [comment]
Awesome thanks!

**Comment by i-schuetz** [comment]
Implemented! You can now rotate the chart after initialization.

Example:
```swift
func onSelected(slice: PieSlice, selected: Bool) {
chartView.referenceAngle = 270 - slice.view.midAngle.radiansToDegrees + chartView.referenceAngle
}
```

Where 270 is the top center, the angle you want to rotate the chart to.

While this doesn't affect the calculations, it's worth to note that the slice's mid angle is not necessarily in [0, 2π] range. If you want to have it in this range, e.g. to debug you can do `slice.view.midAngle.radiansToDegrees.truncatingRemainder(dividingBy: 360)`.

You'll also have to use 0 as `selectedOffset` for now. To support both `selectedOffset` and rotation change it's necessary to do a little more work. You can try to do this if you want! The most simple way to achieve this would be to add a delegate method for termination of rotate animation and also allow to select slices programmatically, such that you can do this when the rotation animation finishes. Or the other way around, depending on what you need.

The change is in master, to use it:
```ruby
pod 'PieCharts', :git => 'https://github.com/i-schuetz/PieCharts.git'
```

**Comment by Brandon-316** [comment]
Great thank you!
