### ISSUE TITLE
Cant add data to piechart properly

### ISSUE THREAD

**Issue by rahulbbit** [i-schuetz/PieCharts#15]
I ma facing an issue while adding data to pie chart from coredata, I am inserting new data with the method **insertSlice** and then **lineTextLayerSettings.label.textGenerator** this method is called and in it i am using for loop fetch data and the pie is inserted at 0 and the text is inserted at last. Can u help in this matter?

**Comment by rahulbbit** [comment]
lineTextLayerSettings.label.textGenerator = {slice in
                
                tempMuttableArray.removeAllObjects()
                
                for each in self.arrayOfExpenses
                {
                    tempMuttableArray.add(each.category!)
                }
                
                tempMuttableArray.exchangeObject(at: tempMuttableArray.count-1, withObjectAt: 0)
                
                return tempMuttableArray.object(at: slice.data.id) as! String
                
            }

**Comment by i-schuetz** [comment]
Could you please post / upload a complete example where the issue can be reproduced?

**Comment by rahulbbit** [comment]
[SampleTabbar.zip](https://github.com/i-schuetz/PieCharts/files/965984/SampleTabbar.zip)

This is my sample example in which on **SAVE** method i am adding data to core data.

**Comment by i-schuetz** [comment]
Hi,

sorry for the delay!

I added a method to the pie chart model such that you can set your `Transactions` object directly in the models and only have to pick it up in the text generators. This simplifies the code and fixes errors.

Additionally I added a method `clear()` to `PieChart` to remove everything from the chart such that it has a clear state before loading in `onResume` (without having to re-add `PieChart` itself).

Also commented some not used outlets.

So far my tests it seems to be working. Attached the zip with the corrections.

I edited `PieCharts` in place though. To get it properly fixed please download the current master version. If you're using cocoapods you need:

```ruby
pod 'PieCharts', :git => 'https://github.com/i-schuetz/PieCharts.git'
```

Let me know if everything works!



[SampleTabbar.zip](https://github.com/i-schuetz/PieCharts/files/974462/SampleTabbar.zip)

**Comment by rahulbbit** [comment]
Thanx at done, sir. But i am not using cocoapods, not a fan. But still i will use it for this. Your solution works. Thanks

**Comment by i-schuetz** [comment]
You don't have to! You also can just download it. I just meant to say that you have to use master. If you're using Carthage let me know and I'll upload a new version soon.
