### ISSUE TITLE
Bouce when chart first animates

### ISSUE THREAD

**Issue by wfgilman** [i-schuetz/PieCharts#17]
Any chance we can add an option to have the chart bounce (spring dampening) when it first draws?

**Comment by i-schuetz** [comment]
Who exactly is "we"? :)

**Comment by wfgilman** [comment]
Haha, I tend to use that voice a lot. I guess I meant is this something that could be a feature request you could implement? Or, I could try to implement it and submit a PR (but I'm not sure where the drawing is actually executed).

**Comment by i-schuetz** [comment]
You can try to do it! I have 0 time these days to implement it but happy to review & merge pull requests.
