### ISSUE TITLE
Dynamically insert PieCustomViewsLayer?

### ISSUE THREAD

**Issue by utsengar** [i-schuetz/PieCharts#18]
Can I do something like:

    func onSelected(slice: PieSlice, selected: Bool) {
        if selected {
            chartView.layers = [createCustomViewsLayer()]
        }
     }

Also also tried adding it while creating the chartView but then when I hide all layers by default (container view), I am not able to set `isHidden=false` in `onSelected`

I am trying to add a uibezierpath around the selected slice, something like this:

![file](https://user-images.githubusercontent.com/137799/26846233-e58c4bca-4aad-11e7-9ba6-cc964546f9c0.png)

**Comment by i-schuetz** [comment]
I think this is not possible right now but feel free to adapt the code, it's nicely organized (I hope) and should be easy to follow... Don't have time currently to do this myself, sorry :(

**Comment by utkarsh2012** [comment]
Sure thanks for the reply! Wil try to implement it.

**Comment by gaminilesh** [comment]
Hello utsengar,
How To set Center Title Text "$14,862 US bonds"?

**Comment by utsengar** [comment]
@gaminilesh I haven't implemented it but to do that, you will need to insert a UIView (with a label) inside the chart and match the size of UIView so that its inside the chart.
