### ISSUE TITLE
If I'm not using Storyboard, what's the approach?

### ISSUE THREAD

**Issue by edurd** [i-schuetz/PieCharts#19]
I have my project just in code, is there a way to use this Chart in a project like this?

**Comment by edurd** [comment]
Never mind..

var resultChart : PieChart = {
        let view = PieChart()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

**Comment by i-schuetz** [comment]
A bit late, but anyway: There's an example in the project for creating the chart programmatically.
