### ISSUE TITLE
How can i refresh slices?

### ISSUE THREAD

**Issue by editor83** [i-schuetz/PieCharts#2]
Hi ivan, i want to update my pie chart values? How can i do?

**Comment by i-schuetz** [comment]
That's currently not supported!

**Comment by diogo10** [comment]
Hi @editor83 ,

You can delete the subview chart dynamically on viewWillAppear and create it again....


```
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
       
        //remove subviews
        view.subviews.forEach({ $0.removeFromSuperview() })
        
        //label view
        label.text = "\(views!) views"
        view.addSubview(label)
        
        //add chart
        chartView = PieChart(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height))
        chartView.delegate = self
        chartView.models = createModels()
        chartView.layers = [createCustomViewsLayer(), createTextLayer(), createTextWithLinesLayer()]
        view.addSubview(chartView)
        chartView.setNeedsDisplay()
        
      
    }
```

**Comment by i-schuetz** [comment]
That's right. I forgot to mention this, thanks!

I was thinking on a clean transition where slides are animated from their current state to the new state. For now re-adding as described by @editor83 is the way to go.

**Comment by i-schuetz** [comment]
Added a method `clear()` to `PieChart` which removes all the content from UI and models. To refresh now you can call `clear()` and re-add everything instead of re-adding `PieChart`.

**Comment by GaneshKumarSelvam** [comment]
There is no any method name clear()?
