### ISSUE TITLE
How give to all pie-slices a rounded edge ?

### ISSUE THREAD

**Issue by Gaantz** [i-schuetz/PieCharts#24]
I'm on the search of how give to all round an edge like this image.
![ScreenShot](https://i.stack.imgur.com/Fl2IZ.png)
Find this link, but that does not work, please someone help.
https://stackoverflow.com/questions/31912903/how-to-draw-arc-with-curved-edge-in-ios
Thanks.

**Comment by i-schuetz** [comment]
You would have to adjust the library to do this, it's not supported. Happy to accept pull requests.
