### ISSUE TITLE
Updating pie chart when data changed

### ISSUE THREAD

**Issue by karzler** [i-schuetz/PieCharts#28]
The value property of a model in the pie chart is a 'let' constant. So that cannot be modified.
Other way i could figure out was to set models to empty and create models again, but that added two piecharts, one on top of another.

Is there a clear precise way to update the chart with changing the values of the pie chart models?

Expected Behavior: The pie chart should update the slices when the data is changed.
Observed Behavior: The value property cannot be set. The updated chart shows up only when the app is started again. 

How do you recommend to update the chart when the data is changed?

UPDATE:

I am now able to update the chart, but I am still unable to show just the updated values in the text layer. The older text layers also show up despite removing all of them before setting the new labels.

pieChart.models = []
pieChart.removeSlices()
// now create models -> this updates the chart. However the previous text layers still show up.

**Comment by karzler** [comment]
Apparently, it was a tiny mistake on my side. I was recreating text layers multiple times. 

For folks looking out how to update the chart, simple set models to empty, and then create models again. Make sure you remove the slices before creating the new models

**Comment by zas9vf** [comment]
hey @karzler. im having the issue where the old labels aren't getting removed. Im using a redux like approach when updating my pie chart but for some reason, the old labels won't go away. This is what i have:

        chartView.models.removeAll()
        chartView.removeSlices()
        chartView.layers.removeAll()
        
        self.chartView.models = state.pieSlices


        chartView.layers = [createTextLayer()] <- this function creates new labels with updated values

how'd you remove the old labels?

I'd appreciate the help here

**Comment by yh2015** [comment]
Hey @zas9vf, I struggled a bit to remove the old labels. In my case I used
        ```
        self.chartView.removeSlices()
        self.chartView.layers.removeAll()
        self.chartView.models.removeAll()
```
and initialized text layer as a global variable in the page 

`var textLayer = PiePlainTextLayer()`

Each time i needed to update the chart i used this code:

`self.textLayer.clear()`

Then update the layers using the method that exists in the tutorial 

```
 let textLayerSettings = PiePlainTextLayerSettings()
                                textLayerSettings.viewRadius = 100
                                textLayerSettings.hideOnOverflow = false
                                textLayerSettings.label.textColor = UIColor.white
                                textLayerSettings.label.font = UIFont.systemFont(ofSize: 15)
                                
                                let formatter = NumberFormatter()
                                formatter.maximumFractionDigits = 1
                                textLayerSettings.label.textGenerator = {slice in
                                      return formatter.string(from: slice.data.percentage * 100 as NSNumber).map{_ 
                                      }
                                }
                                self.textLayer.settings = textLayerSettings
                                self.chartView.layers = [self.textLayer]
```

I hope this helps.

**Comment by zas9vf** [comment]
I had to do some edits to the source code itself to get what I wanted but appreciate the help! 👍🏽
