### ISSUE TITLE
PieCharts Not Initializable Without Nib Files

### ISSUE THREAD

**Issue by nitrogenice** [i-schuetz/PieCharts#3]
Hi, I wanted to used PieCharts without any xib files (one of our team's project protocols.) However, it seems like PieChart is not usable without the use of xib files.

I think the probable cause would be within PieChart.swift, where convenience init() does not seem to call sharedInit() in PieChart.swift, and the overridden init(frame: CGRect) { ... } is declared internally. 

It would be great if you can look into it. Thanks. 👍

**Comment by i-schuetz** [comment]
Fixed in https://github.com/i-schuetz/PieCharts/pull/4
