### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by jimijon** [i-schuetz/PieCharts#41]
After all the parent SwiftCharts is now supporting 4

**Comment by i-schuetz** [comment]
I'll do it this weekend!

**Comment by omerCoosto** [comment]
Any updates? (can you update the pod version also to avoid pointing to a commit via the podfile)

**Comment by jimijon** [comment]
well??? still waiting ... that weekend is three weekends ago

**Comment by i-schuetz** [comment]
Sorry for that, it has been in my mind but haven't found the time. I'll try to do it soon (I'm guessing this weekend but will not put my word on it this time).

Now, since I see some sense of urgency here, remember that you also always can do a pull request :)

**Comment by i-schuetz** [comment]
Well, this is funny, the library was already supporting 4.0... I just forgot to update the readme. Anyway, released a new version, with the latest additions.
