### ISSUE TITLE
want to change start angle

### ISSUE THREAD

**Issue by studiogaram** [i-schuetz/PieCharts#6]
I'm using it well but I want to change angle that start point of first pie slice.

is there a method to change angle of chart in release version (0.04) ?

**Comment by i-schuetz** [comment]
This is now in master. You can use master directly with:
```ruby
pod 'PieCharts', :git => 'https://github.com/i-schuetz/PieCharts.git'
```

**Comment by studiogaram** [comment]
Really Thank you!! 😊 ☺️ 🙏
