### ISSUE TITLE
Personalizate DoughnutDemo

### ISSUE THREAD

**Issue by Laynay** [i-schuetz/PieCharts#7]
It is not a real problem but a clarification

Hi, i'm using your library is good and can be used in many ways! 

I'm using your library in my project but first i'm trying in your demo project, i'm looking to personalizate the Doughnut but for me your library is not easy, i tried to modificate something and i'm getti what i want, but not at all.

I'm gonna to personalizate the slices, where i want only two slices, 1st is the main and the 2nd will be modificate by code frequently(for that i can remove the last and create a new or i can modificate the currently slice), i want a single percentage in the middle (i have already set the text in the middle point of the doughnut but when i add slice i have a label over another).

Have you some suggestion for my question?

Thank you in advance.

**Comment by i-schuetz** [comment]
If I understand the first problem correctly, you want to update slices, that's currently not possible. You have to re-create the complete chart. The second problem, you should be able to adjust the radius of the chart labels in order to not to overlap with the percentage? If this is not the problem please post a screenshot.

**Comment by Laynay** [comment]
ok, i understand, i thought it could be refreshed in some way. The percentage will be in the center of the circle.
Thank you for the time.

**Comment by i-schuetz** [comment]
Ok. What I meant with the percentage, is that if you have overlaps with the labels of the chart, you can adjust the radius of those labels such that they don't overlap.

There's a feature request to be able to update slices https://github.com/i-schuetz/PieCharts/issues/2 but I'm a bit scarce of time now so it will take a while until it's implemented (unless someone else does it).

**Comment by Laynay** [comment]
Ok, i thought i can remove a slice in a certain index, but for now i have only this: chartView.removeSlices()

How can i remove a Slice (with index or if isn't possible just like the last)?

**Comment by i-schuetz** [comment]
There's no support for update or delete yet. Only insert. Please look at the README ;)

**Comment by Laynay** [comment]
Then i can't change the percentage / value of the entire slice?

**Comment by i-schuetz** [comment]
No as mentioned above it's not possible to update or delete individual slices yet. You can re-initialize the chart with updated values. Feel free to submit a PR to help to improve this.
