### ISSUE TITLE
Can I know how to use labelGenerator for using customized label?

### ISSUE THREAD

**Issue by studiogaram** [i-schuetz/PieCharts#8]
I want to use label with slice name and percentage that are styled differently  (e.g. **Apple** 27%, **Samsung** 12%... ) on textLineChart with NSmutableAttributedString,
so I found this code in PieChartLabelSettings.swift 

`
// Optional custom label - when this is set presentations settings (textColor, etc.) are ignored
`
`
    public var labelGenerator: ((PieSlice) -> UILabel)?
`

Can I use 'labelGenerator' for making customized label? or is there any method?

**Comment by i-schuetz** [comment]
Yes, you can use `labelGenerator` for this. Closing this since you are adding support for attributed string in https://github.com/i-schuetz/PieCharts/pull/9
